name: IotaOS CI Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Trigger on version tags too
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ISO & Bootloader Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso grub-pc-bin mtools

      - name: Setup i686-elf GCC Cross-Compiler
        run: |
          echo "Downloading pre-compiled OSdev toolchain..."
          wget -q https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          unzip -q i686-elf-tools-linux.zip -d /tmp/i686-elf-toolchain
          
          # Add the downloaded bin folder to the GitHub Actions PATH
          echo "/tmp/i686-elf-toolchain/bin" >> $GITHUB_PATH

      - name: Verify Toolchain
        run: |
          i686-elf-gcc --version
          i686-elf-ld --version

      - name: Compile IotaOS
        run: make clean && make

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IotaOS-Stable-ISO
          path: build/IotaOS.iso